version: "3.9"
services:
  deep-research:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-research
    container_name: deep-research
    environment:
      - ACCESS_PASSWORD=$ACCESS_PASSWORD
      - GOOGLE_GENERATIVE_AI_API_KEY=$GOOGLE_GENERATIVE_AI_API_KEY
      - GOOGLE_GENERATIVE_AI_API_BASE_URL=$GOOGLE_GENERATIVE_AI_API_BASE_URL
      - API_PROXY_BASE_URL=$API_PROXY_BASE_URL
      - OPENROUTER_API_KEY=$OPENROUTER_API_KEY
      - OPENROUTER_API_BASE_URL=$OPENROUTER_API_BASE_URL
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - OPENAI_API_BASE_URL=$OPENAI_API_BASE_URL
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - ANTHROPIC_API_BASE_URL=$ANTHROPIC_API_BASE_URL
      - DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
      - DEEPSEEK_API_BASE_URL=$DEEPSEEK_API_BASE_URL
      - XAI_API_KEY=$XAI_API_KEY
      - XAI_API_BASE_URL=$XAI_API_BASE_URL
      - OPENAI_COMPATIBLE_API_KEY=$OPENAI_COMPATIBLE_API_KEY
      - OPENAI_COMPATIBLE_API_BASE_URL=$OPENAI_COMPATIBLE_API_BASE_URL
      - POLLINATIONS_API_BASE_URL=$POLLINATIONS_API_BASE_URL
      - OLLAMA_API_BASE_URL=$OLLAMA_API_BASE_URL
      - TAVILY_API_KEY=$TAVILY_API_KEY
      - TAVILY_API_BASE_URL=$TAVILY_API_BASE_URL
      - FIRECRAWL_API_KEY=$FIRECRAWL_API_KEY
      - FIRECRAWL_API_BASE_URL=$FIRECRAWL_API_BASE_URL
      - EXA_API_KEY=$EXA_API_KEY
      - EXA_API_BASE_URL=$EXA_API_BASE_URL
      - BOCHA_API_KEY=$BOCHA_API_KEY
      - BOCHA_API_BASE_URL=$BOCHA_API_BASE_URL
      - SEARXNG_API_BASE_URL=$SEARXNG_API_BASE_URL
      - NEXT_PUBLIC_DISABLED_AI_PROVIDER=$NEXT_PUBLIC_DISABLED_AI_PROVIDER
      - NEXT_PUBLIC_DISABLED_SEARCH_PROVIDER=$NEXT_PUBLIC_DISABLED_SEARCH_PROVIDER
      - NEXT_PUBLIC_MODEL_LIST=$NEXT_PUBLIC_MODEL_LIST
      - HEAD_SCRIPTS=$HEAD_SCRIPTS
    ports:
      - "3333:3000"
